### PR TITLE
Added Linux support

### PR DESCRIPTION
**Pull request by asdfjkluiop**
This adds Linux support for running under mono, a Linux native build of wadpacker is required for building wads.

### CODE REVIEW

**Comment by ZoeyZolotova** [comment]
@asdfjkluiop could you tell me where you got a Linux build of wadpacker?

**Comment by asdfjkluiop** [comment]
@ZoeyZolotova I have no idea honestly. I got them a long time ago when looking for Linux tools to dump my wii nand and never deleted them, I have all the source files for them as they were distributed as source under GPLv2 so I can make a repo and just push them or I can add them to this PR. The folder I have contains source files and a makefile which builds wadpacker, wadunpacker, wadsignchecker, and imet_signer.

**Comment by ZoeyZolotova** [comment]
Hi @asdfjkluiop sorry it's taken so long to get to this. Have you actually been able to run a wad generated by your wadpacker? I've been trying to use one i found, but it just gives me a black screen after the n64 logo. If yours works, could you please provide the source code in a repo or attach it here.

**Comment by asdfjkluiop** [comment]
Last I used it it worked https://github.com/asdfjkluiop/wadpacker

**Comment by ZoeyZolotova** [comment]
Hmm, something must be wrong with my dolphin emulator then, because that is also giving me a black screen after the n64 logo. And I even tried the wadpacker bundled with the randomizer on my windows pc and it's also giving a black screen.. but it works at home. I'll look into it further when I get home.

Thank you for providing that so quickly. Been searching everywhere for it.

**Comment by ZoeyZolotova** [comment]
Looks like I just needed a beta version of dolphin. Should be able to add this support soon.

**Comment by ZoeyZolotova** [comment]
If you could, can you please try what's on the dev branch? It's working on my mac, and in theory it has been working since whenever it was that I made the changes to the directories. I just made a commit to handle paths a little nicer for the CLI.

**Pull request closed without merging**
